language: c++
dist: trusty
sudo: required

git:
  depth: 1

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libssl-dev
            - valgrind
            - pandoc

install:
  - export CC=gcc
  - export CFLAGS="-g -O0 --coverage"
  - export CXX=g++
  - export CXXFLAGS="-g -O0 --coverage"
  - export LDFLAGS="--coverage"

script:
  - git clean -dfx
  - ./autogen.sh
  - ./configure && make -j2 && make check
